channels:
 - conda-forge
 - bioconda
 - pytorch
dependencies:
 - conda-forge::h5py
 - conda-forge::llvmlite
 - conda-forge::numba
 - conda-forge::networkx
 - conda-forge::joblib
 - conda-forge::python-igraph
 - conda-forge::louvain
 - conda-forge::cython
 - conda-forge::click
 - conda-forge::pytorch
 - pytorch::pytorch
 - pytorch::torchvision
 - pytorch::torchaudio
 - conda-forge::cudatoolkit=11.6
 - bioconda::samtools=1.12
 - pip
 - pip:
   - anndata
   - fa2
   - scanpy
   - scipy
   - scrublet
   - scikit-learn
   - phate
   - PhenoGraph
   - leidenalg
   - plotly
   - iplotter
   - cellbrowser
   - scvelo
   - pybind11
   - hnswlib
   - velocyto
   - umap-learn
   - matplotlib
   - matplotlib-inline
   - ipykernel
   - nbconvert
   - squidpy
   - itables
   - spatialde
   - seaborn
   - cellpose
